### ISSUE TITLE
Setup a project structure 

### ISSUE THREAD

**Issue by veeshy** [fastresearchgroup/TACOCAT#12]
A structure helps make the code more modular and importable in other people’s project. No perfect structure exists but a popular one is https://www.patricksoftwareblog.com/structure-of-a-python-project/

This structure lends itself nicely to installation and/or distribution via pip or conda. Also adds a testing dir for your unit tester of choice (pytest is my fav) which also makes future CI efforts a lot easier (github offers a few for OSS like this!)

Really cool project yall!

**Comment by lcarasik** [comment]
This can also be used as a template: https://github.com/uwescience/shablona

**Comment by lcarasik** [comment]
It's about ready, it's the first of a few pull requests to start with. Likely need to separate out geometry, fluid properties, fuel properties, and correlations as the code grows more. Also implementation of a test suite is the next big change.

**Comment by lcarasik** [comment]
Need to add the last bits to get it working as a module, i.e. init.py files.

**Comment by lcarasik** [comment]
Got files reorganized around, trying to get it work again, but not there yet.

**Comment by sierratutwiler** [comment]
Did the last pull request close this issue or is there more that needs to be done for setting up the project structure? Issue #14 specifies adding the testing suite structure.

**Comment by lcarasik** [comment]
@veeshy If you get a chance, do you think we are missing anything in the current main directory?

**Comment by veeshy** [comment]
Structure looks good for the scope the original article mentioned. Next good steps would be to make the project installable so you can import it from anywhere, [pyproject-toml](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/) and that would lead nicely into using GitHub-actions to setup [automated tests](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python)

**Comment by lcarasik** [comment]
Awesome, I'll make a separate issue and close this one.
