### ISSUE TITLE
Set up testing suite

### ISSUE THREAD

**Issue by sierratutwiler** [fastresearchgroup/TACOCAT#14]
Create testing suite for verification files

**Comment by lcarasik** [comment]
Looks like we were recommended setting it up using pytest https://docs.pytest.org/en/stable/

**Comment by lcarasik** [comment]
Please go through this as well!

http://www.patricksoftwareblog.com/python-unit-testing-structuring-your-project/

**Comment by lcarasik** [comment]
This has been addressed in PR #43.
