### ISSUE TITLE
Create read in file for TACOCAT inputs

### ISSUE THREAD

**Issue by sierratutwiler** [fastresearchgroup/TACOCAT#18]
Create a code file format for users to fill in information such as reactor geometry, coolant, and fuel types that TACOCAT will call in, read, and run according to the specified conditions.

**Comment by sierratutwiler** [comment]
Input file has been created and worked into TACOCAT, issue can be closed.

**Comment by lcarasik** [comment]
It exists, but we will need to add more features in the future.
