### ISSUE TITLE
Add fluid properties for FLiBe (molten salt)

### ISSUE THREAD

**Issue by sierratutwiler** [fastresearchgroup/TACOCAT#2]
Add the properties for FLiBe molten salt so we can do single heated channel analysis for a FLiBe molten salt reactor.

**Comment by lcarasik** [comment]
Add the fluid properties from the recommendations by Romatoski et al. 2017

[Romatoski 2017 - Fluoride salt coolant properties for nuclear reactor applications - A review.pdf](https://github.com/fastresearchgroup/TACOCAT/files/4417209/Romatoski.2017.-.Fluoride.salt.coolant.properties.for.nuclear.reactor.applications.-.A.review.pdf)

**Comment by lcarasik** [comment]
Fix the last issue associated with running the verification file (i.e. mac vs. wandows) and we're good to go.

**Comment by lcarasik** [comment]
This was closed by pull request #4
