### ISSUE TITLE
Add the backbone for switching fluid properties in TACOCAT

### ISSUE THREAD

**Issue by lcarasik** [fastresearchgroup/TACOCAT#5]
In order for pull request #2 to be valuable, we need to add the ability to change fluid properties in the main python script (TACOCAT.py). 

This should require a general thermalprops.py module that is imported and the options are picked based on what the user wants.

**Comment by sierratutwiler** [comment]
This can probably be closed since #22 covers the need to fix the coolant selection from if/else to dictionaries and m ove it from tacocat main.

**Comment by FranklinTrevor** [comment]
This issue is resolved in pull request #42 @lcarasik 

Pull request 42 added dictionary file for coolant properties

**Comment by lcarasik** [comment]
This has been resolved. Future work will be to simplify the existing code for it and add documentation (a page) that discusses the fluid properties and where we got them from.
