### ISSUE TITLE
Create runner file for TACOCAT 

### ISSUE THREAD

**Issue by lcarasik** [fastresearchgroup/TACOCAT#8]
A feature that would be useful is run TACOCAT using a runner file (i.e. either we call TACOCAT.py or have TACOCAT.py use an input file) to control the various attributes of the single channel solver.

Need to look into what is the more modern approach.

**Comment by veeshy** [comment]
I like the library configobj for input files

**Comment by sierratutwiler** [comment]
This might be able to closed now that we have TC inputs.

**Comment by lcarasik** [comment]
This has been completed with recent PRs.
